(require :sb-bsd-sockets)
(defpackage net-test
  (:use :sb-bsd-sockets :cl))
(in-package net-test)
(defvar *socket* (make-instance 'inet-socket :type :stream :protocol :tcp))
(socket-connect *socket* #(127 0 0 1) 8000)
(defun send-string (str socket-stream)
  (format socket-stream "~A~%" str)
  (force-output socket-stream))
(let ((socket-stream (socket-make-stream *socket* :output t :input t)))
  (let ((line (read-line)))
    (send-string line socket-stream))
  (print (read-line socket-stream))
  (close socket-stream))
